# Generated by Django 4.2.5 on 2023-10-16 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_product_img_product_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='date_consult',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
