# Generated by Django 4.2.5 on 2023-10-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contacto_date_consult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'order_date'},
        ),
    ]
